- name: Creates /etc/kubernetes/pki/etcd directory
  file:
    path: /etc/kubernetes/pki
    state: directory
- name: CA cert files from master0 to master1 and master2
  synchronize: 
    src: /etc/kubernetes/pki/etcd 
    dest: /etc/kubernetes/pki
  delegate_to: "{{ groups['all-masters'][0] }}"