- name: Start firewalld
  service: 
    name: firewalld 
    state: restarted

- name: Enable firewalld service
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld
    enabled: yes

- name: Open port 6443
  shell: firewall-cmd --permanent --add-port=6443/tcp

- name: Open port 10250
  shell: firewall-cmd --permanent --add-port=10250/tcp

- name: Open port 10255
  shell: firewall-cmd --permanent --add-port=10255/tcp

- name: Open port 10053
  shell: firewall-cmd --permanent --add-port=10053/tcp

- name: Open port 10053
  shell: firewall-cmd --permanent --add-port=10053/udp

- name: Open port 2379
  shell: firewall-cmd --permanent --add-port=2379/tcp

- name: Open port 2380
  shell: firewall-cmd --permanent --add-port=2380/tcp

- name: Enable firewalld. Allow everything
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    rich_rule: 'rule family="ipv4" source address="0.0.0.0/0" destination address="0.0.0.0/0" accept'

- name: Enable firewalld. Allow forward traffic
  firewalld:
    immediate: yes
    permanent: yes
    state: enabled
    rich_rule: 'rule family="ipv4" source address="0.0.0.0/0" destination address="0.0.0.0/0" masquerade'

- name: Reload firewalld
  shell: firewall-cmd --reload