- import_playbook: docker.yaml
- import_playbook: kubeadm.yaml
- import_playbook: setup-firewalld.yaml
- import_playbook: ha-etcd.yaml
- import_playbook: keepalived.yaml
- import_playbook: kubernetes-masters.yaml
- import_playbook: podpreset.yaml
- import_playbook: kubernetes-add-workers.yaml
- import_playbook: encrypting-secrets.yaml
- import_playbook: heapster.yaml
- import_playbook: smoke-test.yaml